### ISSUE TITLE
csv.Error: field larger than field limit

### ISSUE THREAD

**Issue by LingTJ** [oolonek/ISDB#2]
Hello, ISDB guys,
Thank you for the wonderful ISDB software.
Recently I ran a big dataset (a mixture of dataset from Bruker MTQ-II and QE-focus, with about 77 Mbit of mgf and 30 Mbit of out files), but failed after a 30 hours of calculation.
It showed "_csv.Error: field larger than field limit" (please see the picture). Is the LCMS dataset too big?
Could you please give me any instruction?
![screenshot from 2017-07-27](https://user-images.githubusercontent.com/30512870/28697908-055944fc-7372-11e7-9750-44989a0bd202.png)

TJ Ling

**Comment by oolonek** [comment]
Hello @LingTJ  !

The problem is that the fields AllFiles and AllGroups can be extremely large when you treat large datasets. Try to open them in excel and you will see. 
The solution is to remove them, you shouldn't need them anyway. You can do this in excel or other similar software. For convenience and to treat large csv or tab delimited text file we prefer to use R in Rstudio. The following R code will allow you to remove the selected columns and save the resulting output. 

Good luck !

oo1on

```
#load required package
library(data.table)

#set your working directory
setwd("/Users/yourname/yourdirectory/")
data <- fread("your_large_attributes_file.out", drop = c("AllFiles","AllGroups"))

write.table(data, file = "your_attributes_files_cleaned.out", sep="\t", row.names=FALSE)
```
